### ISSUE TITLE
Security concern

### ISSUE THREAD

**Issue by ninoM** [flamelink/gatsby-source-flamelink#10]
Hey if I would like to deploy to Netlify and would like a rebuild every time an update happens in Flamelink, how would I do it without commiting service account credentials JSON?

**Comment by jperasmus** [comment]
Hey, thanks for the question.

There are 2 parts to doing this. One would be setting up your CI/CD in Netlify and the other part is getting a notification when something changes for the build to kick off.

For the second part, we will be releasing "Webhooks" functionality within the next couple of days that you can use for exactly this purpose.

For the first part, I would recommend not committing your service account credentials file into your repo, but using Netlify's environment variables to store your private key in there and then reading the env var from within the Gatsby config file. That is, as far as I am aware, the way most people work with these types of credential files, whether that is the Firebase service account or something else.

https://www.netlify.com/docs/continuous-deployment/#environment-variables

**Comment by jperasmus** [comment]
Here is a link to the Webhooks feature: https://intercom.help/flamelink/en/articles/3057369-webhooks
