### ISSUE TITLE
Nested editor/wysiwyg fields are not transformed

### ISSUE THREAD

**Issue by jperasmus** [flamelink/gatsby-source-flamelink#15]
Root-level editor fields (WYSIWYG, CKEditor & Markdown) have their nodes expanded with the relevant media type. This needs to be done for nested editor fields inside repeater and field group fields as well.

**Comment by jperasmus** [comment]
This functionality has been implemented for nested field groups (not repeaters yet). It is a breaking change, so will be part of v3 of this plugin, but it can be installed with `npm i gatsby-source-flamelink@next` in the mean time.

**Comment by caweidmann** [comment]
This is on the latest release, `v3.0.0`.
