### ISSUE TITLE
_fl_meta_ createdDate and lastModifiedDate not accessible

### ISSUE THREAD

**Issue by EirikOsnes** [flamelink/gatsby-source-flamelink#27]
The _fl_meta_ fields of createdDate and lastModifiedDate are not accessible through GraphQL, even though they exist on the articles on Firebase:
![image](https://user-images.githubusercontent.com/25607450/81396284-69056480-9125-11ea-87b9-8cd6ee0d740e.png) ![image](https://user-images.githubusercontent.com/25607450/81396385-a538c500-9125-11ea-8267-f5398ad5c539.png)

**Comment by caweidmann** [comment]
Hi @EirikOsnes 

We'll be taking a look at this issue this week.

**Comment by caweidmann** [comment]
Hi @EirikOsnes 

Thank you for logging this issue. We have resolved the bug and it will be in an upcoming release.

**Comment by caweidmann** [comment]
If you need the changes in the mean time you can get them by using our `next` package.
```
npm i gatsby-source-flamelink@next
```

**Comment by caweidmann** [comment]
This is on the latest release, `v3.0.0`.
