### ISSUE TITLE
Support downloading images to local & transformation with sharp

### ISSUE THREAD

**Issue by d4rekanguok** [flamelink/gatsby-source-flamelink#5]
If `gatsby-source-flamelink` downloads remote images to local files, users can include images when building static sites, take advantage of Gatsby's responsive image solution such as [gatsby-image](https://www.gatsbyjs.org/packages/gatsby-image/), and reduce their Firebase's storage usage.

After a brief discussion with @jperasmus in the [slack channel](https://flamelink.io/slack), we drew out a basic plan:
- download all assets, either thru flamelink sdk with [`app.storage.getFiles`](https://flamelink.github.io/flamelink/#/storage?id=getfiles) or [`gsutils`](https://cloud.google.com/storage/docs/gsutil/commands/cp)
- cache it with Gatsby
- attach it to image fields

This issue will be used to track the development of this feature!

**Comment by jperasmus** [comment]
Thanks for taking this on, @d4rekanguok

**Comment by PatrickResponsive** [comment]
Thanks @d4rekanguok Could you please give an update on your progress?
👍
